table AMZN
	lineageTag: 5002d1be-f810-4624-b5cb-e686713c2207

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: bff70838-aafe-43cd-82d8-8867bed1cc0f
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 32b2194d-649b-4d68-aa36-f7f76de56cdf
			defaultHierarchy: LocalDateTable_1f3ffac3-61d2-4c64-8013-bdaf89f3ffff.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 74a73143-1911-4788-94ae-eb2adb45b087
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: f94e0615-39a4-46e3-b897-e93851382df5
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: f95f36ef-cc5c-4cb6-b2dc-ea0c1216e8f3
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: e9c6717c-8c2c-4d94-899b-30b5d0a72db7
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: d55c0c56-c277-433d-b748-10e2aee73c19
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: b518e429-4442-4dd3-b310-80bbd23e85b9
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Shaikh Auto Garage\git_demo\PBIProTraining\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

